# Generated by Django 6.0.4 on 2026-04-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ поддержки'),
        ),
    ]
